const express = require('express')
const router = express.Router()
const authController = require('../controllers/auth')
const upload = require('../helpers/multer');

router.post('/getToken', authController.getToken)
router.post('/register', authController.register)
router.post('/login', authController.login)
router.post('/logout', authController.logout)
router.post('/verifyEmail', authController.verifyEmail)
router.post('/familyRole', authController.familyRole)
router.post('/getUserList', authController.getUserList)
router.post('/getUserProfile', authController.getUserProfile)
router.post('/updateUserProfile', authController.updateUserProfile)
router.post('/profileImage', upload.single('file'), authController.profileImage)
router.post('/sendMessage', authController.sendMessage)
router.post('/sendVerificationCode', authController.sendVerificationCode)
router.post('/verifyCode', authController.verifyCode)
router.post('/userReport', authController.userReport)
router.post('/dashboardCount', authController.dashboardCount)
router.post('/userDownloadExcel', authController.userDownloadExcel)
router.post('/getInactiveUserCounts', authController.getInactiveUserCounts)
router.post('/getActiveUsersCount', authController.getActiveUsersCount)
router.post('/weightUpdatePregMom', authController.weightUpdatePregMom)
router.post('/updateWeightDateForPregMoms', authController.updateWeightDateForPregMoms)
router.post('/getUsersByAgeWiseReport', authController.getUsersByAgeWiseReport)
// router.post('/getMobileOtp', authController.getMobileOtp)
router.post('/verifyMobileOtp', authController.verifyMobileOtp)
router.post('/activeInactiveUserExcel', authController.activeInactiveUserExcel)
router.post('/ageWiseUserExcel', authController.ageWiseUserExcel)
router.post('/trimesterExcel', authController.trimesterExcel)
router.post('/weekExcel', authController.weekExcel)
router.post('/trimesterCounts', authController.trimesterCounts)
router.post('/trimesterCounts', authController.trimesterCounts)
router.post('/weekCounts', authController.weekCounts)
router.post('/delete', authController.delete)
router.post('/DeeplinkGenerate', authController.DeeplinkGenerate)
// router.post('/mobileUpdateAndRequestOtp', authController.mobileUpdateAndRequestOtp)
router.post('/decodeToken', authController.decodeToken)
router.post('/requestOtpForMobile', authController.requestOtpForMobile)
router.post('/verifyOtpForMobile', authController.verifyOtpForMobile)

module.exports = router;    