const express = require('express')
const router = express.Router()
const exerciseSubscriptionController = require('../controllers/exerciseSubscription')

router.post('/add', exerciseSubscriptionController.add)
router.post('/list', exerciseSubscriptionController.list)
router.post('/view', exerciseSubscriptionController.view)
router.post('/update', exerciseSubscriptionController.update)
router.post('/delete', exerciseSubscriptionController.delete)
router.post('/userSubscription', exerciseSubscriptionController.userSubscription)
router.post('/userPlanlist', exerciseSubscriptionController.userPlanlist)
router.post('/activateUserPlan', exerciseSubscriptionController.activateUserPlan)
// router.post('/subscriptionDownloadExcel', exerciseSubscriptionController.subscriptionDownloadExcel)
// router.post('/userPlanScript', exerciseSubscriptionController.userPlanScript)
router.post('/createOrder', exerciseSubscriptionController.createOrder)
router.post('/verify', exerciseSubscriptionController.verify)
router.post('/verifyPaymentStatus', exerciseSubscriptionController.verifyPaymentStatus)
router.post('/cancelCheckoutOrder', exerciseSubscriptionController.cancelCheckoutOrder)
router.post('/paymentFailed', exerciseSubscriptionController.paymentFailed)
router.post('/verifyPaymentAndSubscribe', exerciseSubscriptionController.verifyPaymentAndSubscribe)
router.post('/applePaymentFailed', exerciseSubscriptionController.applePaymentFailed)
router.post('/applePaymentCancelled', exerciseSubscriptionController.applePaymentCancelled)

module.exports = router;    
